services:
  db:
    image: mysql:5.7
    container_name: redmine-db
    restart: always
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - ./data/mysql:/var/lib/mysql

  redmine:
    image: redmine:latest
    container_name: redmine
    restart: always
    ports:
      - "8085:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
    depends_on:
      - db
    volumes:
      - ./redmine:/usr/src/redmine
      - ./data/files:/usr/src/redmine/files
